wandb_version: 1

SEED:
  desc: null
  value: 42
DATASET:
  desc: null
  value:
    datadir: /home/inho/df_detection/experiments_xception/data/
    dataname: dataset4
    mode: train
OPTIMIZER:
  desc: null
  value:
    opt_name: Adam
    lr: 0.001
TRAINING:
  desc: null
  value:
    batch_size: 32
    test_batch_size: 32
    epochs: 50
    log_interval: 100
    use_scheduler: true
    amp: 'True'
    consistency_rate: 1.0
MODEL:
  desc: null
  value:
    pretrain_path: /media/data2/jiwon/DeepfakeAD/recog_model.pt
    amp: true
    model_name: xception
    pre_logits: 'False'
RESULT:
  desc: null
  value:
    savedir: /media/data1/inho/df_detection/experiments_OC/saved_model/final/
MODIFYING:
  desc: null
  value: 'False'
EXP_NAME:
  desc: null
  value: xception_OC-dataset4
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700063112.436312
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.7.16
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
