SEED: 42

DATASET:
  datadir: '/home/inho/df_detection/experiments_xception/data/'
  dataname: 'dataset4'
  mode: 'test'

OPTIMIZER:
  opt_name: Adam
  lr: 0.001

TRAINING:
  batch_size: 32
  test_batch_size: 32
  epochs: 50
  log_interval: 100
  use_scheduler: true

MODEL:
  pretrain_path: '/media/data1/inho/df_detection/experiments_OC/saved_model/df_real/df_real/modifided/0_state_dict.pth'

RESULT:
  savedir: '/media/data1/inho/df_detection/experiments_OC/saved_model/'