SEED: 42

DATASET:
  datadir: '/home/inho/df_detection/experiments_xception/data/'
  dataname: 'dataset4'
  mode: 'test'

OPTIMIZER:
  opt_name: Adam
  lr: 0.001

TRAINING:
  batch_size: 32
  test_batch_size: 32
  epochs: 20
  log_interval: 100
  use_scheduler: true
  amp: true

MODEL:
  pretrain_path: '/media/data2/jiwon/DeepfakeAD/recog_model.pt'
  pretrain_path2: '/home/inho/df_detection/experiments_OC/model/xception-43020ad28.pth'

RESULT:
  savedir: '/media/data1/inho/df_detection/experiments_OC/saved_model/final/'