SEED: 42

DATASET:
  datadir: /home/inho/df_detection/experiments_xception/data/

OPTIMIZER:
  opt_name: Adam
  lr: 0.001

TRAINING:
  batch_size: 32
  test_batch_size: 32
  epochs: 50
  log_interval: 100
  use_scheduler: true

RESULT:
  savedir: '/media/data1/inho/df_detection/experiments_xception/saved_model/'